### ISSUE TITLE
add nanoseconds to DFGVariable and DFGFactor

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/DistributedFactorGraphs.jl#474] opened 2020-05-19 18:34 UTC
Julia `DateTime` dispatch only computes down to millisecond, but we frequently want micro or nanosecond.  To be fully compatible with ROS we should probably add a nanosecond offset memory location to.  I'd like to get this in for DFG v0.8.0.

**Comment by dehann** [comment] 2020-05-19 18:36
Suggested mechanism is to remove all subsecond from the `timestamp` field and store that separately at `nanosecond::Int64` scale (similar to ROS).  We'd need to do some logic to make it easy to use too.

**Comment by Affie** [comment] 2020-05-19 20:23
Is issue a duplicate of #367?
I was looking at it and best i could think of was to use `UTInstant{T}`.
I tend to agree with adding it in solver data as there is no specific standard time. 
The original idea behind variable timestamp was more for a standard time for things like database and searching and not as a variable for calculations.

**Comment by GearsAD** [comment] 2020-05-22 13:46
Current DB is ISO8601 with .fff, like timestamp:2020-05-22T08:38:49.797. As discussed we'll add an additional Int64 field with nanosecond resolution for the subsecond component, and additional functions to get/set/ the high-res timer.

**Closed** 2020-05-27 06:58 UTC
Labels: feature request, timing, types
